# Generated by Django 3.2.9 on 2022-07-07 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='localhost:8000/', max_length=6)),
                ('full_url', models.URLField(unique=True, verbose_name='Длинная ссылка')),
                ('hash_url', models.SlugField(verbose_name='Короткая ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ссылка пользователя',
                'verbose_name_plural': 'Ссылки пользователей',
                'ordering': ('-created_at',),
            },
        ),
    ]
